#ifndef KORALL_HTTP_INTERNAL_H
#define KORALL_HTTP_INTERNAL_H
#include "arena/arena.h"
#include "socket/socket.h"
#include "utils/utils.h"
#include "config/config.h"
#include "korall/http.h"

#define WS_VERSION 13
#define WS_KEY_LEN 24
#define WS_GUID "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
#define WS_GUID_LEN 36

#define MAX_HTTP_METHOD_STR_LEN 7
#define MAX_HTTP_QUERY_STR_LEN 1024
#define MAX_HTTP_URL_LEN (2 * KILOBYTE) // incl query str: https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string/48230425#48230425
#define HTTP_PROT_LEN 8
#define MAX_DOMAIN_LEN 255
#define MAX_DOMAIN_LABEL_LEN 63
#define MIN_DOMAIN_LABEL_LEN 1
#define MAX_HTTP_BODY_LEN MEGABYTE // todo: 1mb?
#define MAX_HTTP_BODY_DIGIT_LEN 7 // 7 digits
#define MAX_HTTP_HEADER_FIELD_LEN 32 // todo: allow custom headers (longer header field?)
#define MAX_HTTP_HEADER_VALUE_LEN 4096 // todo: cookie? // https://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key
#define MAX_HTTP_USER_AGENT (4 * KILOBYTE)

#define MAX_MEDIA_TYPE_LEN 73
#define MAX_HTTP_BOUNDARY_LEN 70
#define MAX_ACCEPT_ENCODING_CHAR_LEN 8
#define MAX_ACCEPT_LANGUAGE_CHAR_LEN 7
#define MAX_TE_LEN 8
#define MAX_TRANSFER_ENCODING_LEN 8
#define MAX_HTTP_CHARSET_LEN 12
#define MAX_HTTP_REQ_CC_LEN 14
#define MAX_HTTP_RES_CC_LEN 21
#define MAX_REASON_PHRASE_LEN 34
#define MAX_CONTENT_ENCODING_CHAR_LEN 8
#define MAX_DELTA_ALGORITHM_CHAR_LEN 8
#define MAX_HTTP_CC_SEC_CHAR_LEN 8
#define MAX_HTTP_CC_SEC 31536000 // https://stackoverflow.com/a/25201898

// request

#define HTTP_REQ_START_LINE_LEN (MAX_HTTP_METHOD_STR_LEN + 1 + MAX_HTTP_URL_LEN + 1 + HTTP_PROT_LEN + 2)
#define HTTP_REQ_HEADER_LEN (8 * KILOBYTE)
#define HTTP_REQ_HEADER_COUNT 100
#define HTTP_REQ_HEADERS_LEN (HTTP_REQ_HEADER_LEN * HTTP_REQ_HEADER_COUNT)
#define HTTP_REQ_BODY_LEN (1 * MEGABYTE) // todo: change to 1 GB?
#define HTTP_REQ_SIZE (HTTP_REQ_START_LINE_LEN + HTTP_REQ_HEADERS_LEN + HTTP_REQ_BODY_LEN)
#define HTTP_REQ_ARENA_SIZE (HTTP_REQ_SIZE + KILOBYTE)

// response

#define HTTP_RES_START_LINE_LEN (HTTP_PROT_LEN + 1 + 3 + MAX_REASON_PHRASE_LEN + 2)
#define HTTP_RES_HEADER_LEN (8 * KILOBYTE)
#define HTTP_RES_HEADER_COUNT 100
#define HTTP_RES_HEADERS_LEN (HTTP_RES_HEADER_LEN * HTTP_RES_HEADER_COUNT)
#define HTTP_RES_BODY_LEN (1 * MEGABYTE)
#define HTTP_RES_SIZE (HTTP_RES_START_LINE_LEN + HTTP_RES_HEADERS_LEN + HTTP_RES_BODY_LEN)
#define HTTP_RES_ARENA_SIZE (HTTP_RES_SIZE + KILOBYTE)
#define HTTP_RES_FULL_ARENA_SIZE HTTP_RES_SIZE


#define MAX_DATE_STR_LEN 29
// https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url#comment117272662_55468411

#define ERROR_MESSAGE(err, msg) \
    "{\n" \
    "\t\"error\": \"" err "\",\n" \
    "\t\"message\": \"" msg "\"\n" \
    "}"

#define HTTP_REQ_CC_HAS_VAL(x) (x == HTTP_REQ_CC_MAX_AGE || x == HTTP_REQ_CC_MAX_STALE || x == HTTP_REQ_CC_MIN_FRESH || x == HTTP_REQ_CC_STALE_IF_ERROR)
#define HTTP_RES_CC_HAS_VAL(x) (x == HTTP_RES_CC_MAX_AGE || x == HTTP_RES_CC_S_MAX_AGE || x == HTTP_RES_CC_STALE_WHILE_REVALIDATE || x == HTTP_RES_CC_STALE_IF_ERROR)

typedef enum {
	HTTP_METHOD_UNUSED = -1,
	HTTP_CONNECT,
	HTTP_DELETE,
	HTTP_GET,
	HTTP_HEAD,
	HTTP_OPTIONS,
	HTTP_PATCH,
	HTTP_POST,
	HTTP_PUT,
	HTTP_TRACE,
	HTTP_METHOD_COUNT
} HTTPMethod;

typedef enum {
	HTTP_PROT_1_0,
	HTTP_PROT_1_1,
} HTTPProtocol;

typedef enum {
	HTTP_RQH_A_IM,
	HTTP_RQH_ACCEPT,
	HTTP_RQH_ACCEPT_CHARSET,
	HTTP_RQH_ACCEPT_DATETIME,
	HTTP_RQH_ACCEPT_ENCODING,
	HTTP_RQH_ACCEPT_LANGUAGE,
	HTTP_RQH_ACCESS_CONTROL_REQUEST_METHOD,
	HTTP_RQH_ACCESS_CONTROL_REQUEST_HEADERS,
	HTTP_RQH_AUTHORIZATION,
	HTTP_RQH_CACHE_CONTROL,
	HTTP_RQH_CONNECTION,
	HTTP_RQH_CONTENT_ENCODING,
	HTTP_RQH_CONTENT_LENGTH,
	HTTP_RQH_CONTENT_MD5,
	HTTP_RQH_CONTENT_TYPE,
	HTTP_RQH_COOKIE,
	HTTP_RQH_DATE,
	HTTP_RQH_EXPECT,
	HTTP_RQH_FORWARDED,
	HTTP_RQH_FROM,
	HTTP_RQH_HOST,
	HTTP_RQH_HTTP2_SETTINGS,
	HTTP_RQH_IF_MATCH,
	HTTP_RQH_IF_MODIFIED_SINCE,
	HTTP_RQH_IF_NONE_MATCH,
	HTTP_RQH_IF_RANGE,
	HTTP_RQH_IF_UNMODIFIED_SINCE,
	HTTP_RQH_MAX_FORWARDS,
	HTTP_RQH_ORIGIN,
	HTTP_RQH_PRAGMA,
	HTTP_RQH_PREFER,
	HTTP_RQH_PROXY_AUTHORIZATION,
	HTTP_RQH_RANGE,
	HTTP_RQH_REFERER,
	HTTP_RQH_TE,
	HTTP_RQH_TRAILER,
	HTTP_RQH_TRANSFER_ENCODING,
	HTTP_RQH_USER_AGENT,
	HTTP_RQH_UPGRADE,
	HTTP_RQH_VIA,
	HTTP_RQH_WARNING,
	HTTP_RQH_WS_KEY,
	HTTP_RQH_WS_VERSION,
	HTTP_RQH_COUNT
} HTTPRequestHeaderField;

typedef enum {
	HTTP_RSH_ACCEPT_CH,
	HTTP_RSH_ACCESS_CONTROL_ALLOW_ORIGIN,
	HTTP_RSH_ACCESS_CONTROL_ALLOW_CREDENTIALS,
	HTTP_RSH_ACCESS_CONTROL_EXPOSE_HEADERS,
	HTTP_RSH_ACCESS_CONTROL_MAX_AGE,
	HTTP_RSH_ACCESS_CONTROL_ALLOW_METHODS,
	HTTP_RSH_ACCESS_CONTROL_ALLOW_HEADERS,
	HTTP_RSH_ACCEPT_PATCH,
	HTTP_RSH_ACCEPT_RANGES,
	HTTP_RSH_AGE,
	HTTP_RSH_ALLOW,
	HTTP_RSH_ALT_SVC,
	HTTP_RSH_CACHE_CONTROL,
	HTTP_RSH_CONNECTION,
	HTTP_RSH_CONTENT_DISPOSITION,
	HTTP_RSH_CONTENT_ENCODING,
	HTTP_RSH_CONTENT_LANGUAGE,
	HTTP_RSH_CONTENT_LENGTH,
	HTTP_RSH_CONTENT_LOCATION,
	HTTP_RSH_CONTENT_MD5,
	HTTP_RSH_CONTENT_RANGE,
	HTTP_RSH_CONTENT_TYPE,
	HTTP_RSH_DATE,
	HTTP_RSH_DELTA_BASE,
	HTTP_RSH_ETAG,
	HTTP_RSH_EXPIRES,
	HTTP_RSH_IM,
	HTTP_RSH_LAST_MODIFIED,
	HTTP_RSH_LINK,
	HTTP_RSH_LOCATION,
	HTTP_RSH_P3P,
	HTTP_RSH_PRAGMA,
	HTTP_RSH_PREFERENCE_APPLIED,
	HTTP_RSH_PROXY_AUTHENTICATE,
	HTTP_RSH_PUBLIC_KEY_PINS,
	HTTP_RSH_RETRY_AFTER,
	HTTP_RSH_SERVER,
	HTTP_RSH_SET_COOKIE,
	HTTP_RSH_STRICT_TRANSPORT_SECURITY,
	HTTP_RSH_TRAILER,
	HTTP_RSH_TRANSFER_ENCODING,
	HTTP_RSH_TK,
	HTTP_RSH_UPGRADE,
	HTTP_RSH_VARY,
	HTTP_RSH_VIA,
	HTTP_RSH_WARNING,
	HTTP_RSH_WWW_AUTHENTICATE,
	HTTP_RSH_X_FRAME_OPTIONS,
	HTTP_RSH_COUNT,
} HTTPResponseHeaderField;

typedef enum {
	HTTP_SC_100 = 100,
	HTTP_SC_101 = 101,
	HTTP_SC_102 = 102,
	HTTP_SC_103 = 103,
	HTTP_SC_200 = 200,
	HTTP_SC_201 = 201,
	HTTP_SC_202 = 202,
	HTTP_SC_203 = 203,
	HTTP_SC_204 = 204,
	HTTP_SC_205 = 205,
	HTTP_SC_206 = 206,
	HTTP_SC_207 = 207,
	HTTP_SC_208 = 208,
	HTTP_SC_209 = 209,
	HTTP_SC_226 = 226,
	HTTP_SC_300 = 300,
	HTTP_SC_301 = 301,
	HTTP_SC_302 = 302,
	HTTP_SC_303 = 303,
	HTTP_SC_304 = 304,
	HTTP_SC_305 = 305,
	HTTP_SC_306 = 306,
	HTTP_SC_307 = 307,
	HTTP_SC_308 = 308,
	HTTP_SC_400 = 400,
	HTTP_SC_401 = 401,
	HTTP_SC_402 = 402,
	HTTP_SC_403 = 403,
	HTTP_SC_404 = 404,
	HTTP_SC_405 = 405,
	HTTP_SC_406 = 406,
	HTTP_SC_407 = 407,
	HTTP_SC_408 = 408,
	HTTP_SC_409 = 409,
	HTTP_SC_410 = 410,
	HTTP_SC_411 = 411,
	HTTP_SC_412 = 412,
	HTTP_SC_413 = 413,
	HTTP_SC_414 = 414,
	HTTP_SC_415 = 415,
	HTTP_SC_416 = 416,
	HTTP_SC_417 = 417,
	HTTP_SC_418 = 418,
	HTTP_SC_421 = 421,
	HTTP_SC_422 = 422,
	HTTP_SC_423 = 423,
	HTTP_SC_424 = 424,
	HTTP_SC_425 = 425,
	HTTP_SC_426 = 426,
	HTTP_SC_428 = 428,
	HTTP_SC_429 = 429,
	HTTP_SC_431 = 431,
	HTTP_SC_444 = 444,
	HTTP_SC_451 = 451,
	HTTP_SC_499 = 499,
	HTTP_SC_500 = 500,
	HTTP_SC_501 = 501,
	HTTP_SC_502 = 502,
	HTTP_SC_503 = 503,
	HTTP_SC_504 = 504,
	HTTP_SC_505 = 505,
	HTTP_SC_506 = 506,
	HTTP_SC_507 = 507,
	HTTP_SC_508 = 508,
	HTTP_SC_509 = 509,
	HTTP_SC_510 = 510,
	HTTP_SC_511 = 511,
	HTTP_SC_599 = 599,
	HTTP_SC_COUNT = 65,
} HTTPStatusCode;

typedef enum {
	HTTP_MT_UNUSED = -1,
	HTTP_MT_ANY,
	HTTP_MT_APP,
	HTTP_MT_APP_JSON,
	HTTP_MT_APP_LD_JSON,
	HTTP_MT_APP_MSWORD,
	HTTP_MT_APP_PDF,
	HTTP_MT_APP_SQL,
	HTTP_MT_APP_VND_API_JSON,
	HTTP_MT_APP_VND_MS_PORT_EXEC,
	HTTP_MT_APP_VND_MS_XLS,
	HTTP_MT_APP_VND_MS_PPT,
	HTTP_MT_APP_VND_ODT,
	HTTP_MT_APP_VND_PPTX,
	HTTP_MT_APP_VND_XLSX,
	HTTP_MT_APP_VND_DOCX,
	HTTP_MT_APP_X_WWW_FORM_URLENCODED,
	HTTP_MT_APP_XML,
	HTTP_MT_APP_XHTML_XML,
	HTTP_MT_APP_ZIP,
	HTTP_MT_APP_ZSTD,
	HTTP_MT_AUD,
	HTTP_MT_AUD_MPEG,
	HTTP_MT_AUD_OGG,
	HTTP_MT_IMG,
	HTTP_MT_IMG_AVIF,
	HTTP_MT_IMG_WEBP,
	HTTP_MT_IMG_JPEG,
	HTTP_MT_IMG_PNG,
	HTTP_MT_IMG_SVG_XML,
	HTTP_MT_IMG_TIFF,
	HTTP_MT_MOD,
	HTTP_MT_MOD_OBJ,
	HTTP_MT_MTP,
	HTTP_MT_MTP_FORM_DATA,
	HTTP_MT_TXT,
	HTTP_MT_TXT_PLAIN,
	HTTP_MT_TXT_CSS,
	HTTP_MT_TXT_CSV,
	HTTP_MT_TXT_HTML,
	HTTP_MT_TXT_JS,
	HTTP_MT_TXT_XML,
	HTTP_MT_COUNT
} HTTPMediaType;

typedef enum {
	HTTP_ACCENC_ANY,
	HTTP_ACCENC_GZIP,
	HTTP_ACCENC_COMPRESS,
	HTTP_ACCENC_DEFLATE,
	HTTP_ACCENC_BR,
	HTTP_ACCENC_ZSTD,
	HTTP_ACCENC_DCB,
	HTTP_ACCENC_DCZ,
	HTTP_ACCENC_IDENTITY,
	HTTP_ACCENC_COUNT
} HTTPAcceptEncoding;

typedef enum {
	HTTP_TE_ANY,
	HTTP_TE_GZIP,
	HTTP_TE_COMPRESS,
	HTTP_TE_DEFLATE,
	HTTP_TE_TRAILERS,
	HTTP_TE_COUNT
} HTTPTe;

typedef enum {
	HTTP_TRENC_ANY,
	HTTP_TRENC_GZIP,
	HTTP_TRENC_COMPRESS,
	HTTP_TRENC_DEFLATE,
	HTTP_TRENC_CHUNKED,
	HTTP_TRENC_COUNT
} HTTPTransferEncoding;

typedef enum {
	HTTP_CHS_UNUSED = -1,
	HTTP_CHS_BIG5,
	HTTP_CHS_EUC_KR,
	HTTP_CHS_ISO_8859_1,
	HTTP_CHS_ISO_8859_2,
	HTTP_CHS_ISO_8859_3,
	HTTP_CHS_ISO_8859_4,
	HTTP_CHS_ISO_8859_5,
	HTTP_CHS_ISO_8859_6,
	HTTP_CHS_ISO_8859_7,
	HTTP_CHS_ISO_8859_8,
	HTTP_CHS_KOI8_R,
	HTTP_CHS_SHIFT_JIS,
	HTTP_CHS_X_EUC,
	HTTP_CHS_UTF_8,
	HTTP_CHS_WINDOWS_1250,
	HTTP_CHS_WINDOWS_1251,
	HTTP_CHS_WINDOWS_1252,
	HTTP_CHS_WINDOWS_1253,
	HTTP_CHS_WINDOWS_1254,
	HTTP_CHS_WINDOWS_1255,
	HTTP_CHS_WINDOWS_1256,
	HTTP_CHS_WINDOWS_1257,
	HTTP_CHS_WINDOWS_1258,
	HTTP_CHS_WINDOWS_874,
	HTTP_CHS_COUNT,
} HTTPCharset;

typedef enum {
	HTTP_CON_UNUSED = -1,
	HTTP_CON_KEEP_ALIVE,
	HTTP_CON_CLOSE,
	HTTP_CON_UPGRADE,
	HTTP_CON_COUNT,
} HTTPConnection;

typedef enum {
	HTTP_REQ_CC_UNUSED = -1,
	HTTP_REQ_CC_MAX_AGE,
	HTTP_REQ_CC_MAX_STALE,
	HTTP_REQ_CC_MIN_FRESH,
	HTTP_REQ_CC_NO_CACHE,
	HTTP_REQ_CC_NO_STORE,
	HTTP_REQ_CC_NO_TRANSFORM,
	HTTP_REQ_CC_ONLY_IF_CACHED,
	HTTP_REQ_CC_STALE_IF_ERROR,
	HTTP_REQ_CC_COUNT,
} HTTPRequestCacheControl;

typedef enum {
	HTTP_EXP_UNUSED = -1,
	HTTP_EXP_100_CONTINUE
} HTTPExpect;

typedef enum {
	HTTP_UPG_UNUSED = -1,
	HTTP_UPG_WS,
	HTTP_UPG_COUNT,
} HTTPUpgrade;

typedef enum {
	HTTP_CONENC_GZIP,
	HTTP_CONENC_COMPRESS,
	HTTP_CONENC_DEFLATE,
	HTTP_CONENC_BR,
	HTTP_CONENC_ZSTD,
	HTTP_CONENC_DCB,
	HTTP_CONENC_DCZ,
	HTTP_CONENC_COUNT,
} HTTPContentEncoding;

typedef enum {
	HTTP_DELT_ALG_VCDIFF,
	HTTP_DELT_ALG_DIFFE,
	HTTP_DELT_ALG_GZIP,
	HTTP_DELT_ALG_GDIFF,
	HTTP_DELT_ALG_DEFLATE,
	HTTP_DELT_ALG_RANGE,
	HTTP_DELT_ALG_IDENTITY,
	HTTP_DELT_ALG_COUNT
} HTTPDeltaAlgorithm;

// response

typedef enum {
	HTTP_RES_CC_UNUSED = -1,
	HTTP_RES_CC_MAX_AGE,
	HTTP_RES_CC_S_MAX_AGE,
	HTTP_RES_CC_NO_CACHE,
	HTTP_RES_CC_NO_STORE,
	HTTP_RES_CC_NO_TRANSFORM,
	HTTP_RES_CC_MUST_REVALIDATE,
	HTTP_RES_CC_PROXY_REVALIDATE,
	HTTP_RES_CC_MUST_UNDERSTAND,
	HTTP_RES_CC_PRIVATE,
	HTTP_RES_CC_PUBLIC,
	HTTP_RES_CC_IMMUTABLE,
	HTTP_RES_CC_STALE_WHILE_REVALIDATE,
	HTTP_RES_CC_STALE_IF_ERROR,
	HTTP_RES_CC_COUNT,
} HTTPResponseCacheControl;

// errors

typedef enum {
	// todo
	HTTP_BAD_A_IM = -36,
	HTTP_BAD_ACCEPT_LANG = -35,
	HTTP_BAD_CONTENT_ENC = -34,
	HTTP_BAD_WS_KEY_CALC = -33,
	HTTP_BAD_WS_KEY = -32,
	HTTP_BAD_WS_VERSION = -31,
	HTTP_BAD_UPGRADE = -30,
	HTTP_BAD_TK = -29,
	HTTP_BAD_MAX_FORWARDS = -28,
	HTTP_BAD_TRANSFER_ENCODING = -27,
	HTTP_BAD_TE = -26,
	HTTP_REQUEST_TARGET_TOO_BIG = -25,
	HTTP_BAD_SERVER = -24,
	HTTP_BODY_TOO_LONG = -23,
	HTTP_BODY_NOT_ALLOWED = -22,
	HTTP_BAD_EXPECT = -21,
	HTTP_BAD_DATE = -20,
	HTTP_BAD_USER_AGENT = -19,
	HTTP_BAD_CACHE_CONTROL = -18,
	HTTP_BAD_CONNECTION = -17,
	HTTP_BAD_ACCESS_CONTROL_REQUEST_HEADERS = -16,
	HTTP_BAD_ACCESS_CONTROL_REQUEST_METHOD = -15,
	HTTP_BAD_CONTENT_TYPE = -14,
	HTTP_BAD_CONTENT_LENGTH = -13,
	HTTP_BAD_ACCEPT_ENC = -12,
	HTTP_BAD_ACCEPT = -11,
	HTTP_BAD_PROT = -10,
	HTTP_BAD_HEADER_VAL = -9,
	HTTP_BAD_HEADER = -8,
	HTTP_BAD_PORT = -7,
	HTTP_BAD_DOMAIN = -6,
	HTTP_BAD_DOMAIN_PORT = -5,
	HTTP_BAD_REQUEST_TARGET = -4,
	HTTP_BAD_METHOD = -3,
	HTTP_BAD_REQUEST = -2,
	HTTP_ERROR = -1,
	HTTP_SUCCESS = 0,
} HTTPError;

// Request

struct HTTPRequestStartLineInternal {
	char* request_target;
	HTTPMethod method;
	HTTPProtocol protocol;
};

// Headers

struct HTTPHeaderHostInternal {
	char* domain;
	char* port;
};

struct HTTPRequestWebsocketInternal {
	char* accept;
	bool has_connection;
	bool has_upgrade;
	bool has_key;
	bool has_version;
};

// Request

struct HTTPRequestInternal {
	HTTPRequestStartLine* start_line;
	HTTPHeaderHost* host;
	char* headers;
	char* body;
	HTTPRequestWebsocket* ws;
};

// Response


struct HTTPResponseInternal {
	String start_line;
	String headers;
	size_t header_count;
	size_t header_capacity;
	size_t header_size;
	char* headers_base;
	String body;
	SSL* ssl;
};

HTTPError http_request_parse(const char* data, HTTPRequest* req);

HTTPError http_process_request_header_value(const HTTPRequestHeaderField field, const char* value, HTTPRequest* req);

HTTPError http_request_process_header(const char** str, HTTPRequest* req);

HTTPError http_request_process_headers(const char** str, HTTPRequest* req);

HTTPError http_request_process_protocol(const char** str, HTTPRequest* req);

HTTPError http_request_process_body(const char* str, HTTPRequest* req);

HTTPError http_request_process_method(const char** str, HTTPRequest* req);

HTTPError http_request_process_target_relative(const char* str, HTTPRequest* req);

HTTPError http_request_process_target_absolute(const char* str, HTTPRequest* req);

HTTPError http_request_process_target(const char** str, HTTPRequest* req);

HTTPError http_request_process_target(const char** str, HTTPRequest* req);

HTTPRequest* http_request_init(Arena* arena);

void http_request_clear(Arena *arena, HTTPRequest** req);

int http_verify_origin(Array* allow_origins, HTTPRequest* req, bool has_creds, char* value, size_t value_len);

int http_allowed_methods(Array* allow_methods, char* value, size_t value_len);

int http_allowed_headers(Array* allow_headers, char* value, size_t value_len);

// Response

HTTPError http_process_response_header_value(const HTTPResponseHeaderField field, const char* value);

int http_response_construct(
	HTTPResponse* res,
	const HTTPRequest *req,
	HTTPStatusCode code,
	HTTPMediaType content_type,
	const char* body
);

int http_response_ws_construct(
	HTTPResponse* res,
	const HTTPRequest *req,
	const char* accept
);

int http_response_send(const SOCKET inc_sock, const HTTPResponse* res);

HTTPResponse* http_response_init(Arena *arena);

void http_response_clear(Arena* arena, HTTPResponse** res);

void http_get_current_date(String *str);

const char* http_error_response_info(HTTPError err, HTTPStatusCode* sc, HTTPMediaType* mt);

#endif