#include "http_.h"
#include "lookup_tables.h"

Flags default_flags = {
	.server_type = ST_HTTP, // todo: move to main.c ?
};

const LookupEntryStrInt flag_lookup_table[FLAG_LOOKUP_TABLE_COUNT] = {
	{"tcp", F_TCP},
	{"http", F_HTTP},
};

const LookupEntryStrInt http_method_lookup_table[HTTP_METHOD_LOOKUP_TABLE_COUNT] = {
	{ "CONNECT", HTTP_CONNECT },
	{ "DELETE", HTTP_DELETE },
	{ "GET", HTTP_GET },
	{ "HEAD", HTTP_HEAD },
	{ "OPTIONS", HTTP_OPTIONS },
	{ "PATCH", HTTP_PATCH },
	{ "POST", HTTP_POST },
	{ "PUT", HTTP_PUT },
	{ "TRACE" , HTTP_TRACE }
};

const LookupEntryStrInt http_req_header_field_lookup_table[HTTP_REQ_HEADER_FIELD_TABLE_COUNT] = {
	{"A-IM", HTTP_RQH_A_IM},
	{"Accept", HTTP_RQH_ACCEPT},
	{"Accept-Charset", HTTP_RQH_ACCEPT_CHARSET},
	{"Accept-Datetime", HTTP_RQH_ACCEPT_DATETIME},
	{"Accept-Encoding", HTTP_RQH_ACCEPT_ENCODING},
	{"Accept-Language", HTTP_RQH_ACCEPT_LANGUAGE},
	{"Access-Control-Request-Method", HTTP_RQH_ACCESS_CONTROL_REQUEST_METHOD},
	{"Access-Control-Request-Headers", HTTP_RQH_ACCESS_CONTROL_REQUEST_HEADERS},
	{"Authorization", HTTP_RQH_AUTHORIZATION},
	{"Cache-Control", HTTP_RQH_CACHECONTROL},
	{"Connection", HTTP_RQH_CONNECTION},
	{"Encoding", HTTP_RQH_CONTENT_ENCODING},
	{"Content-Length", HTTP_RQH_CONTENT_LENGTH},
	{"Content-MD5", HTTP_RQH_CONTENT_MD5},
	{"Content-Type", HTTP_RQH_CONTENT_TYPE},
	//{"Cookie", HTTP_RQH_COOKIE},
	{"Date", HTTP_RQH_DATE},
	{"Expect", HTTP_RQH_EXPECT},
	{"Forwarded", HTTP_RQH_FORWARDED},
	{"From", HTTP_RQH_FROM},
	{"Host", HTTP_RQH_HOST},
	{"HTTP2-Setting", HTTP_RQH_HTTP2_SETTINGS},
	{"If-Match", HTTP_RQH_IF_MATCH},
	{"If-Modified-Since", HTTP_RQH_IF_MODIFIED_SINCE},
	{"If-None-Match", HTTP_RQH_IF_NONE_MATCH},
	{"If-Range", HTTP_RQH_IF_RANGE},
	{"If-Unmodified-Since", HTTP_RQH_IF_UNMODIFIED_SINCE},
	{"Max-Forwards", HTTP_RQH_MAX_FORWARDS},
	{"Origin", HTTP_RQH_ORIGIN},
	{"Pragma", HTTP_RQH_PRAGMA},
	{"Prefer", HTTP_RQH_PREFER},
	{"Proxy-Authorization", HTTP_RQH_PROXY_AUTHORIZATION},
	{"Range", HTTP_RQH_RANGE},
	{"Referer", HTTP_RQH_REFERER},
	{"TE", HTTP_RQH_TE},
	{"Trailer", HTTP_RQH_TRAILER},
	{"Transfer-Encoding", HTTP_RQH_TRANSFER_ENCODING},
	{"User-Agent", HTTP_RQH_USER_AGENT},
	{"Upgrade", HTTP_RQH_UPGRADE},
	{"Via", HTTP_RQH_VIA},
	{"Warning", HTTP_RQH_WARNING},
};

const LookupEntryIntStr http_status_code_lookup_table[HTTP_STATUS_CODE_TABLE_COUNT] = {
	{ HTTP_SC_100, "Continue"},
	{ HTTP_SC_101, "Switching Protocols"},
	{ HTTP_SC_102, "Processing"},
	{ HTTP_SC_103, "Early Hints"},
	{ HTTP_SC_200, "OK"},
	{ HTTP_SC_201, "Created"},
	{ HTTP_SC_202, "Accepted"},
	{ HTTP_SC_203, "Non-Authoritative Information"},
	{ HTTP_SC_204, "No Content"},
	{ HTTP_SC_205, "Reset Content"},
	{ HTTP_SC_206, "Partial Content"},
	{ HTTP_SC_207, "Multi-Status"},
	{ HTTP_SC_208, "Already Reported"},
	{ HTTP_SC_226, "IM Used"},
	{ HTTP_SC_300, "Multiple Choices"},
	{ HTTP_SC_301, "Moved Permanently"},
	{ HTTP_SC_302, "Found"},
	{ HTTP_SC_303, "See Other"},
	{ HTTP_SC_304, "Not Modified"},
	{ HTTP_SC_305, "Use Proxy"},
	{ HTTP_SC_307, "Temporary Redirect"},
	{ HTTP_SC_308, "Permanent Redirect"},
	{ HTTP_SC_400, "Bad Request"},
	{ HTTP_SC_401, "Unauthorized"},
	{ HTTP_SC_402, "Payment Required"},
	{ HTTP_SC_403, "Forbidden"},
	{ HTTP_SC_404, "Not Found"},
	{ HTTP_SC_405, "Method Not Allowed"},
	{ HTTP_SC_406, "Not Acceptable"},
	{ HTTP_SC_407, "Proxy Authentication Required"},
	{ HTTP_SC_408, "Request Timeout"},
	{ HTTP_SC_409, "Conflict"},
	{ HTTP_SC_410, "Gone"},
	{ HTTP_SC_411, "Length Required"},
	{ HTTP_SC_412, "Precondition Failed"},
	{ HTTP_SC_413, "Payload Too Large"},
	{ HTTP_SC_414, "URI Too Long"},
	{ HTTP_SC_415, "Unsupported Media Type"},
	{ HTTP_SC_416, "Requested Range Not Satisfiable"},
	{ HTTP_SC_417, "Expectation Failed"},
	{ HTTP_SC_418, "I'm a teapot"},
	{ HTTP_SC_421, "Misdirected Request"},
	{ HTTP_SC_422, "Unprocessable Entity"},
	{ HTTP_SC_423, "Locked"},
	{ HTTP_SC_424, "Failed Dependency"},
	{ HTTP_SC_425, "Too Early"},
	{ HTTP_SC_426, "Upgrade Required"},
	{ HTTP_SC_428, "Precondition Required"},
	{ HTTP_SC_429, "Too Many Requests"},
	{ HTTP_SC_431, "Request Header Fields Too Large"},
	{ HTTP_SC_444, "Connection Closed Without Response"},
	{ HTTP_SC_451, "Unavailable For Legal Reasons"},
	{ HTTP_SC_499, "Client Closed Request"},
	{ HTTP_SC_500, "Internal Server Error"},
	{ HTTP_SC_501, "Not Implemented"},
	{ HTTP_SC_502, "Bad Gateway"},
	{ HTTP_SC_503, "Service Unavailable"},
	{ HTTP_SC_504, "Gateway Timeout"},
	{ HTTP_SC_505, "HTTP Version Not Supported"},
	{ HTTP_SC_506, "Variant Also Negotiates"},
	{ HTTP_SC_507, "Insufficient Storage"},
	{ HTTP_SC_508, "Loop Detected"},
	{ HTTP_SC_510, "Not Extended"},
	{ HTTP_SC_511, "Network Authentication Required"},
	{ HTTP_SC_599, "Network Connect Timeout Error"}
};

const LookupEntryIntStr http_res_header_field_lookup_table[HTTP_RES_HEADER_FIELD_TABLE_COUNT] = {
	{ HTTP_RSH_ACCEPT_CH, "Accept-CH" },
	{ HTTP_RSH_ACCESS_CONTROL_ALLOW_ORIGIN, "Access-Control-Allow-Origin" },
	{ HTTP_RSH_ACCESS_CONTROL_ALLOW_CREDENTIALS, "Access-Control-Allow-Credentials" },
	{ HTTP_RSH_ACCESS_CONTROL_EXPOSE_HEADERS, "Access-Control-Expose-Headers" },
	{ HTTP_RSH_ACCESS_CONTROL_MAX_AGE, "Access-Control-Max-Age" },
	{ HTTP_RSH_ACCESS_CONTROL_ALLOW_METHODS, "Access-Control-Allow-Methods" },
	{ HTTP_RSH_ACCESS_CONTROL_ALLOW_HEADERS, "Access-Control-Allow-Headers" },
	{ HTTP_RSH_ACCEPT_PATCH, "Accept-Patch" },
	{ HTTP_RSH_ACCEPT_RANGES, "Accept-Ranges" },
	{ HTTP_RSH_AGE, "Age" },
	{ HTTP_RSH_ALLOW, "Allow" },
	{ HTTP_RSH_ALT_SVC, "Alt-Svc" },
	{ HTTP_RSH_CACHE_CONTROL, "Cache-Control" },
	{ HTTP_RSH_CONNECTION, "Connection" },
	{ HTTP_RSH_CONTENT_DISPOSITION, "Content-Disposition" },
	{ HTTP_RSH_CONTENT_ENCODING, "Content-Encoding" },
	{ HTTP_RSH_CONTENT_LANGUAGE, "Content-Language" },
	{ HTTP_RSH_CONTENT_LENGTH, "Content-Length" },
	{ HTTP_RSH_CONTENT_LOCATION, "Content-Location" },
	{ HTTP_RSH_CONTENT_MD5, "Content-MD5" },
	{ HTTP_RSH_CONTENT_RANGE, "Content-Range" },
	{ HTTP_RSH_CONTENT_TYPE, "Content-Type" },
	{ HTTP_RSH_DATE, "Date" },
	{ HTTP_RSH_DELTA_BASE, "Delta-Base" },
	{ HTTP_RSH_ETAG, "ETag" },
	{ HTTP_RSH_EXPIRES, "Expires" },
	{ HTTP_RSH_IM, "IM" },
	{ HTTP_RSH_LAST_MODIFIED, "Last-Modified" },
	{ HTTP_RSH_LINK, "Link" },
	{ HTTP_RSH_LOCATION, "Location" },
	{ HTTP_RSH_P3P, "P3P" },
	{ HTTP_RSH_PRAGMA, "Pragma" },
	{ HTTP_RSH_PREFERENCE_APPLIED, "Preference-Applied" },
	{ HTTP_RSH_PROXY_AUTHENTICATE, "Proxy-Authenticate" },
	{ HTTP_RSH_PUBLIC_KEY_PINS, "Public-Key-Pins" },
	{ HTTP_RSH_RETRY_AFTER, "Retry-After" },
	{ HTTP_RSH_SERVER, "Server" },
	{ HTTP_RSH_SET_COOKIE, "Set-Cookie" },
	{ HTTP_RSH_STRICT_TRANSPORT_SECURITY, "Strict-Transport-Security" },
	{ HTTP_RSH_TRAILER, "Trailer" },
	{ HTTP_RSH_TRANSFER_ENCODING, "Transfer-Encoding" },
	{ HTTP_RSH_TK, "Tk" },
	{ HTTP_RSH_UPGRADE, "Upgrade" },
	{ HTTP_RSH_VARY, "Vary" },
	{ HTTP_RSH_VIA, "Via" },
	{ HTTP_RSH_WARNING, "Warning" },
	{ HTTP_RSH_WWW_AUTHENTICATE, "WWW-Authenticate" },
	{ HTTP_RSH_X_FRAME_OPTIONS, "X-Frame-Options" },
};

const LookupEntryIntStr media_type_lookup_table[MEDIA_TYPE_TABLE_COUNT] = {
	{ MT_APP_JSON, "application/json" },
	{ MT_APP_LD_JSON, "application/ld+json" },
	{ MT_APP_MSWORD, "application/msword" },
	{ MT_APP_PDF, "application/pdf" },
	{ MT_APP_SQL, "application/sql" },
	{ MT_APP_VND_API_JSON, "application/vnd.api+json" },
	{ MT_APP_VND_MS_PORT_EXEC, "application/vnd.microsoft.portable-executable" },
	{ MT_APP_VND_MS_XLS, "application/vnd.ms-excel" },
	{ MT_APP_VND_MS_PPT, "application/vnd.ms-powerpoint" },
	{ MT_APP_VND_ODT, "application/vnd.oasis.opendocument.text" },
	{ MT_APP_VND_PPTX, "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
	{ MT_APP_VND_XLSX, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
	{ MT_APP_VND_DOCX, "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
	{ MT_APP_X_WWW_FORM_URLENCODED, "application/x-www-form-urlencoded" },
	{ MT_APP_XML, "application/xml" },
	{ MT_APP_ZIP, "application/zip" },
	{ MT_APP_ZSTD, "application/zstd" },
	{ MT_AUD_MPEG, "audio/mpeg" },
	{ MT_AUD_OGG, "audio/ogg" },
	{ MT_IMG_AVIF, "image/avif" },
	{ MT_IMG_JPEG, "image/jpeg" },
	{ MT_IMG_PNG, "image/png" },
	{ MT_IMG_SVG_XML, "image/svg+xml" },
	{ MT_IMG_TIFF, "image/tiff" },
	{ MT_MOD_OBJ, "model/obj" },
	{ MT_MTP_FORM_DATA, "multipart/form-data" },
	{ MT_TXT_PLAIN, "text/plain" },
	{ MT_TXT_CSS, "text/css" },
	{ MT_TXT_CSV, "text/csv" },
	{ MT_TXT_HTML, "text/html" },
	{ MT_TXT_JS, "text/javascript" },
	{ MT_TXT_XML, "text/xml" },
};